# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Ozric
version: "0.6.9"
slug: ozric
description: Continuous graph-based automation engine
url: "https://github.com/jchown/ozric-addon/tree/master/OzricAddon"
arch:
  - armv7
  - aarch64
  - amd64
# - i386   (not supported by dotnet, see https://docs.microsoft.com/en-us/dotnet/core/rid-catalog)
#init: false
options:
  logging: "Info"
schema:
  logging: list(Error|Warning|Info|Debug|Trace)
  token: str
homeassistant_api: true
ingress: true
image: "jchown/{arch}-ozric-addon"