# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Ozric
version: "0.5.0"
slug: ozric
description: Ozric graph-based automation
url: "https://github.com/jchown/ozric-addon/tree/master/OzricAddon"
arch:
  - armv7
  - aarch64
  - amd64
#  - i386   (not supported by dotnet, see https://docs.microsoft.com/en-us/dotnet/core/rid-catalog)
#init: false
options:
  logging: "Info"
  graph: "{}"
schema:
  logging: list(Error|Warning|Info|Debug|Trace)
  graph: str
  token: str
homeassistant_api: true
image: "jchown/{arch}-ozric-addon"