# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Ozric
version: "0.1.5"
slug: ozric
description: Ozric graph-based automation
#url: "https://github.com/jchown/ozric-addon/tree/master/OzricAddon"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
#init: false
options:
  message: "A message from Ozric..."
  logging: "Info"
schema:
  message: "str?"
  logging: list(Error|Warning|Info|Debug|Trace)
homeassistant_api: true
#image: "github.com/jchown/ozric"