# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Ozric
version: "0.2.2"
slug: ozric
description: Ozric graph-based automation
#url: "https://github.com/jchown/ozric-addon/tree/master/OzricAddon"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
#init: false
options:
  logging: "Info"
  graph: "{}"
schema:
  logging: list(Error|Warning|Info|Debug|Trace)
  graph: str
homeassistant_api: true
image: "jchown/{arch}-ozric-addon"