# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Ozric
version: "0.10.1"
slug: ozric
description: Continuous graph-based automation engine
url: "https://github.com/jchown/ozric-addon/tree/master/OzricAddon"
arch:
# - armhf  (not supported by dotnet, see https://docs.microsoft.com/en-us/dotnet/core/rid-catalog)
# - armv7  (HA builder not working, see https://github.com/home-assistant/builder/issues/158)
  - aarch64
  - amd64
# - i386   (not supported by dotnet, see https://docs.microsoft.com/en-us/dotnet/core/rid-catalog)
init: false
options:
  logging: "Info"
schema:
  logging: list(Error|Warning|Info|Debug|Trace)
homeassistant_api: true
ingress: true
image: "jchown/{arch}-ozric-addon"
ports:
  8099/tcp: 8099
hassio_api: true
