name: "Publish"

on: push

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Publish x64
        uses: home-assistant/builder@master
        with:
          args: |
            --amd64 \
            --target . \
            --docker-hub jchown
      - name: Publish AArch64
        uses: home-assistant/builder@master
        with:
          args: |
            --aarch64 \
            --target . \
            --docker-hub jchown
      - name: Publish ARM v7
        uses: home-assistant/builder@master
        with:
          args: |
            --armv7 \
            --target . \
            --docker-hub jchown
