name: "Publish"

on: push

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          submodules: 'true'
      - id: dotenv
        name: Set variables
        uses: falti/dotenv-action@v1
      - name: Prepare Dockerfile
        run: |
          sed -i "s/ARG OZRIC_VERSION=.*/ARG OZRIC_VERSION=${{ steps.dotenv.outputs.version }}/" Dockerfile
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Publish x64
        uses: home-assistant/builder@master
        with:
          args: |
            --amd64 \
            --target . \
            --docker-hub jchown \
            --version ${{ steps.dotenv.outputs.version }}
      - name: Publish AArch64
        uses: home-assistant/builder@master
        with:
          args: |
            --aarch64 \
            --target . \
            --docker-hub jchown \
            --version ${{ steps.dotenv.outputs.version }}
      # - name: Publish ARM v7
      #   uses: home-assistant/builder@master
      #   with:
      #     args: |
      #       --armv7 \
      #       --target . \
      #       --docker-hub jchown
